{{- if .Values.externalSecrets.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "birthday-api.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
